### ISSUE TITLE
Keyboard update to reflect Kodi

### ISSUE THREAD

**Issue by ghost** [Sranshaft/skin.immersive#80]
Works brilliantly with Kodi except for they keyboard which appears blank. Would have actually sorted the issue myself, since Kodi has updated how they handle keyboards, but had no idea where to start on this specific issue. I looked in the DialogKeyboard.xml but honestly, I was floating. 

Thanks.

**Comment by jgato** [comment]
Any workaround. In android I have no way of using the keyboard, also my external keyboard remains unsable. For example, I cannot rename files to allow tvshows or movies matching with the scrapper.
